name: mittverk
description: Mittverk Flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.2.0
  dio: ^3.0.7
  flutter_svg: ^0.17.1
  cupertino_icons: ^0.1.2
  fluro: ^1.6.2

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/background.jpg
    # Logos
    - assets/logo/mittverk.svg
    # Vectors