name: mittverk
description: Mittverk Flutter app

version: 2.0.7+39

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  ffi: ^1.0.0
  provider: ^6.0.1
  cookie_jar: ^3.0.1
  dio: ^4.0.4
  shared_preferences: ^2.0.4
  dio_cookie_manager: ^2.0.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.4
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.2.0
  firebase_messaging: ^11.2.4
  time: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/background.jpg
    # Logos
    - assets/logo/gigover.svg
    # Vectors & Icons
    - assets/icons/gear.svg
    - assets/icons/comment.svg
    - assets/icons/pause.svg
    - assets/icons/resume.svg
    - assets/icons/stop.svg
    - assets/icons/timer.svg
    - assets/icons/beach.svg