name: mittverk
description: Mittverk Flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.2.0
  cookie_jar: ^1.0.0
  dio: ^3.0.7
  dio_cookie_manager: 1.0.0
  flutter_svg: ^0.17.1
  cupertino_icons: ^0.1.2
  sliding_up_panel: ^1.0.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.0
  time: ^1.3.0
  flutter_launcher_icons: ^0.7.3
  intl: ^0.16.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/background.jpg
    # Logos
    - assets/logo/mittverk.svg
    # Vectors & Icons
    - assets/icons/gear.svg
    - assets/icons/comment.svg
    - assets/icons/pause.svg
    - assets/icons/resume.svg
    - assets/icons/stop.svg
    - assets/icons/timer.svg